name: Build Firmware Workflow on main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [GPS, LITE]
        server_mode: [BLE, WIFI]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      
      - name: Run PlatformIO Action
        uses: karniv00l/platformio-run-action@v1
        env:
          DEFAULT_MODEL: ${{ matrix.model }}
          DEFAULT_SERVER_MODE: ${{ matrix.server_mode }}
        with:
          environments: "esp32-c3-devkitm-1" # Specify environments, e.g., "env1,env2"
          targets: ""      # Specify targets, e.g., "upload,monitor"
          project-dir: "./Firmware/"  # Specify project directory
          project-conf: "" # Specify a custom platformio.ini
          jobs: ""         # Number of parallel build jobs
          silent: ""       # true/false
          verbose: ""      # true/false
          disable-auto-clean: "" # true/false

      - name: Build Filesystem
        run: pio run -t buildfs -v --project-dir ./Firmware/

      - name: Install esptool.py
        run: |
          python3 -m pip install esptool

      - name: Merge binary files
        run: |
          esptool.py --chip esp32c3 merge_bin \
          --flash_mode dio \
          --flash_freq 40m \
          --flash_size 4MB \
          0x0000 ./Firmware/.pio/build/esp32-c3-devkitm-1/bootloader.bin \
          0x8000 ./Firmware/.pio/build/esp32-c3-devkitm-1/partitions.bin \
          0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin \
          0x10000 ./Firmware/.pio/build/esp32-c3-devkitm-1/firmware.bin \
          0x210000 ./Firmware/.pio/build/esp32-c3-devkitm-1/littlefs.bin \
          -o mcompass-${{ matrix.model }}-${{ matrix.server_mode }}.bin

      - name: Get commit hash
        id: get_commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Upload merged firmware
        uses: actions/upload-artifact@v7
        with:
          name: mcompass-${{ matrix.model }}-${{ matrix.server_mode }}-${{ env.COMMIT_HASH }}
          path: mcompass-${{ matrix.model }}-${{ matrix.server_mode }}.bin
